### ISSUE TITLE
platforming

### ISSUE THREAD

**Issue by blurymind** [axaq/traviso.js#14]
This engine seems to be for making a very specific isometric game type, where you point and click movement with path tracing is only used.

But how about being able to use input from the keyboard and the joypad?
And instead of using path finding on tiles, it lets you move the object in multiple axis - with ability to jump on platforms

examples:
sonic 3d blast
https://www.youtube.com/watch?v=R47qeLEzVEc
landstalker
https://www.youtube.com/watch?v=rh3LT4gl12k

**Comment by axaq** [comment]
Yep true and true. It is using mouse/touch interaction at the moment and that is what it was intended for initially. However, I would assume (I need to double check) it won't be hard to add keyboard controls. Free movement, however, might be slightly harder since we will need a different kind of occlusion detection. 
Feel free to implement and send a PR, otherwise it might take me a while to do so :)
