### ISSUE TITLE
Cannot get map.xml from electron

### ISSUE THREAD

**Issue by Chank1e** [axaq/traviso.js#8]
I would like to use traviso in electron app. So when I try to get map.xml I get error "cannot getElementsByTagName of null"
So responseXML is null,but response has all needed data

**Comment by axaq** [comment]
Hi @Chank1e,
Couldn't replicate the issue but I was in the process of ditching XML anyway so I thought I might as well finish that before responding to you properly :)

[Repo](https://github.com/axaq/traviso.js/), [docs](http://www.travisojs.com/docs/) and the [tutorials](http://www.travisojs.com/blog/) have now been updated with the new version where traviso uses json file in order to load the data. Please, have a look and let me know if this fixes your problem.
